-- Create Schema
CREATE SCHEMA IF NOT EXISTS energy_db;
USE energy_db;

-- Create energy_data table
CREATE TABLE energy_data (
    row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    FSA VARCHAR(10),
    DATE DATE,
    HOUR INT,
    CUSTOMER_TYPE VARCHAR(50),
    PRICE_PLAN VARCHAR(20),
    TOTAL_CONSUMPTION DOUBLE,
    PREDICTED_CONSUMPTION DOUBLE
);
